# -*- mode: ruby -*-
# vi: set ft=ruby :

# Helper for host configuration - 32 or 64 bits systems
require './helper/core'
require './helper/utils'
require './helper/config'

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.synced_folder "../app", "/home/vagrant/app", create: true
  config.vm.synced_folder "../", "/home/vagrant/linc-webapp", create: true

  # Use an Ubuntu box based in the host arch
  arch = Vagrant::Util::Platform::bit64? ? 64 : 32
  config.vm.box = "ubuntu/trusty#{arch}"

  # 5000 for heroky deploy
  config.vm.network :forwarded_port, guest:  5000, host: 5080 # API Port

  config.vm.network :private_network, ip: "192.168.100.20"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/app", "1"]
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/linc-webapp", "1"]
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end

  # Provision without puppet or cheff, using shell scripts
  config.vm.provision :shell, path: "./provision/ubuntu_provision.sh"

  # X11 over ssh
  config.ssh.forward_x11 = true
end
