# -*- mode: ruby -*-
# vi: set ft=ruby :

# LINC is an open source shared database and facial recognition
# system that allows for collaboration in wildlife monitoring.
# Copyright (C) 2016  Wildlifeguardians
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information or to contact visit linclion.org or email tech@linclion.org

# Helper for host configuration - 32 or 64 bits systems
require './helper/core'
require './helper/utils'
require './helper/config'

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.synced_folder "../app", "/home/vagrant/app", create: true
  config.vm.synced_folder "../", "/home/vagrant/linc-webapp", create: true

  # Use an Ubuntu box based in the host arch
  arch = Vagrant::Util::Platform::bit64? ? 64 : 32
  config.vm.box = "ubuntu/trusty#{arch}"

  # 5000 for heroky deploy
  config.vm.network :forwarded_port, guest:  5000, host: 5080 # API Port

  config.vm.network :private_network, ip: "192.168.100.20"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/app", "1"]
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/linc-webapp", "1"]
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end

  # Provision without puppet or cheff, using shell scripts
  config.vm.provision :shell, path: "./provision/ubuntu_provision.sh"

  # X11 over ssh
  config.ssh.forward_x11 = true
end
