name: Deploy to Heroku

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy_env:
        type: choice
        description: 'Deployment Environment'
        required: true
        options:
          - stage
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HEROKU_APP_NAME: ${{ github.event.inputs.deploy_env == 'prod' && 'linc-website' || 'linc-website-staging' }}
    steps:
      - name: Check if deploying to prod from non-main branch
        if: ${{ github.event.inputs.deploy_env == 'prod' && github.ref != 'refs/heads/main' }}
        run: |
          echo "Error: Deployment to production from a branch other than main is not allowed."
          exit 1
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@581dd286c962b6972d427fcf8980f60755c15520 # v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ env.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_SERVICE_ACCOUNT_EMAIL }}
